name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ya jis branch pe tu deploy karna chahta hai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 and restart container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/iot_api_webapp || git clone https://github.com/sharan-sant/iot_api_webapp.git && cd iot_api_webapp
            git pull origin main
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm $(sudo docker ps -aq) || true
            sudo docker build -t iot_api_webapp .
            sudo docker run -d -p 80:5050 iot_api_webapp
          EOF
